backend:
  name: test-repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog_layout" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}

      # Preview image for blog card
      - { label: "Preview Image", name: "image", widget: "image", required: false, hint: "Image for blog card" }
      - { label: "Body", name: "body", widget: "markdown" }

publish_mode: editorial_workflow

